# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-11 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20180911_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='balance',
            field=models.PositiveIntegerField(default=0, verbose_name='可提现和使用余额'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='openid',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='uid',
            field=models.CharField(blank=True, help_text='微信用户绑定和CC视频统计', max_length=64, null=True, unique=True),
        ),
    ]
