# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-11 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20180911_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='uid',
            field=models.CharField(help_text='微信用户绑定和CC视频统计', max_length=64, unique=True),
        ),
    ]
